# ./docker-compose.yml
version: '3'

services:
  web:
    build: .
    container_name: php
    links:
      - db
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "80:80"
      - "443:443"
    stdin_open: true
    tty: true
    networks:
      - webserver

  db:
    container_name: mysql
    image: mysql:8
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: app_user
      MYSQL_DATABASE: app_db
      MYSQL_PASSWORD: app_password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./data/:/var/lib/mysql/
    networks:
      - webserver

  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    links:
      - db
    ports:
      - 8080:8080
    networks:
      - webserver

networks:
  webserver:
    driver: bridge
